// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poafavaegepvipnsvznf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvYWZhdmFlZ2VwdmlwbnN2em5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzQzNTgsImV4cCI6MjA3Mjg1MDM1OH0.YVY4XLIgpe_Nrr2yQ2GlnpplbGpYSPIwFfvapblQCxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});